from ubuntu
maintainer Nick Stinemates <nick@docker.com>

# imagine this exists on github for backup, you have a vundlefile, or something
# similar, this is just me capturing my development environment

add vim /root/.vim
add vimrc /root/.vimrc

volume /root/

# imagine this being vundle install or whatever.
cmd ["true"]
